require 'rubygems'
require 'data_mapper'
require 'yaml'
require 'marc'

require 'uw_catalog/model/bib_data'
require 'uw_catalog/model/location'
require 'uw_catalog/model/holding'
require 'uw_catalog/model/holding_marc'
require 'uw_catalog/model/item'
require 'uw_catalog/model/items_listing'
require 'uw_catalog/voyager_sql'
require 'uw_catalog/voyager_item_status'
require 'uw_catalog/catalog'
require 'uw_catalog/data_loader'
